const Constants = {
// Options: [
//   "FP Knowledge",
//   "IT Knowledge",
//   "Computer Operation Skills",
//   "Sales Ability",
//   "Sales Knowledge",
//   "Applied Skills",
//   "Foreign Language Ability",
//   "Problem-Recognition Ability",
//   "Planning Ability",
//   "Risk Management Ability",
//   "Consideration / Attentiveness",
//   "Objectivity",
//   "Cooperativeness",
//   "Financial Knowledge",
//   "Planning Skills",
//   "Accounting Knowledge",
//   "Curiosity",
//   "Negotiation Skills",
//   "Initiative / Action Ability",
//   "Customer Perspective",
//   "Communication Skills",
//   "Flexibility",
//   "Situational Adaptability",
//   "Product Knowledge",
//   "Information-Gathering Ability",
//   "Speed / Quickness",
//   "Stress Tolerance",
//   "Accuracy",
//   "Production & Manufacturing Technology/Knowledge",
//   "Sense of Responsibility",
//   "Customer Service Skills",
//   "Design Technology/Knowledge",
//   "Persuasiveness",
//   "Creativity",
//   "Spirit of Inquiry",
//   "Teamwork",
//   "Coordination Ability",
//   "Relationship-Building Skills",
//   "Perseverance",
//   "Decision-Making Ability",
//   "Business Manners",
//   "Quality Control Technology/Knowledge",
//   "Real Estate & Construction Knowledge",
//   "Presentation Skills",
//   "Project Management Ability",
//   "Writing Ability",
//   "Analytical Skills",
//   "Marketing Knowledge",
//   "Desire to Learn",
//   "Management Ability",
//   "Sense of Purpose",
//   "Ability to Organize Key Points",
//   "Leadership",
//   "Comprehension Ability",
//   "Logical Thinking Ability",
//   "Document-Creation Ability",
//   "Legal Knowledge",
//   "Consulting Knowledge",
//   "Management Knowledge",
//   "HR Knowledge",
//   "Production Management Knowledge",
// ],

  Options: [
    "FP知識",
    "IT知識",
    "パソコン操作能力",
    "営業力",
    "営業知識",
    "応用力",
    "外国語力",
    "課題認識能力",
    "企画力",
    "危機管理能力",
    "気配り",
    "客観性",
    "協調性",
    "金融知識",
    "計画性",
    "経理知識",
    "好奇心",
    "交渉力",
    "行動力",
    "顧客視点",
    "コミュニケーション能力",
    "柔軟性",
    "状況対応能力",
    "商品知識",
    "情報収集能力",
    "迅速性",
    "ストレス耐性",
    "正確性",
    "生産および製造技術・知識",
    "責任感",
    "接客能力",
    "設計技術・知識",
    "説得力",
    "創造力",
    "探究心",
    "チームワーク",
    "調整力",
    "人間関係構築力",
    "粘り強さ",
    "判断力",
    "ビジネスマナー",
    "品質管理技術・知識",
    "不動産・建築知識",
    "プレゼンテーション能力",
    "プロジェクト管理能力",
    "文章力",
    "分析力",
    "マーケティング知識",
    "向学心",
    "マネジメント能力",
    "目的意識",
    "要点整理能力",
    "リーダーシップ",
    "理解力",
    "論理的思考能力",
    "資料作成能力",
    "法律知識",
    "コンサルティング知識",
    "経営知識",
    "人事知識",
    "生産管理知識",
  ],

//   AdditionalDetails: [
//   "Holds a Financial Planner (FP) qualification and possesses knowledge to provide advice on asset management.",
//   "Has acquired essential knowledge of information systems needed for work.",
//   "Can proficiently use essential software such as Excel and Word for computer-based tasks.",
//   "Can demonstrate the knowledge and skills required for product sales.",
//   "Has acquired the minimum knowledge required for corporate sales.",
//   "Can relate acquired knowledge and know-how and apply basic knowledge to solve complex problems.",
//   "Has the language ability to communicate smoothly with foreign clients or colleagues.",
//   "Understands the cause of problems and can identify the issues that need to be addressed.",
//   "Can organize information and materials and plan new activities according to objectives.",
//   "Can anticipate risks that affect life or assets and prepare and execute methods to avoid them.",
//   "Understands others’ perspectives and can make considerate decisions to facilitate smooth business and negotiations.",
//   "Has a viewpoint that everyone can agree with and can express it clearly.",
//   "Can cooperate with others to progress tasks.",
//   "Possesses the knowledge necessary for financial operations such as selling financial products, financial planning, and loan planning, and can apply it effectively.",
//   "Can determine what needs to be done and by when and act accordingly to achieve goals.",
//   "Has acquired the knowledge necessary to handle accounting operations such as payment processing and issuing invoices or receipts.",
//   "Shows broad curiosity toward unknown things and independently gathers information or takes initiative.",
//   "Can negotiate with people who have different opinions and achieve agreements that align closely with their intentions.",
//   "Can independently carry out necessary actions.",
//   "Can view things from the customer’s perspective and understand their thoughts and needs.",
//   "Understands the intention of the other party and adjusts content and tone based on their level of understanding to communicate effectively.",
//   "Listens to differing opinions without rejecting them and incorporates good points from them.",
//   "Prepares countermeasures for expected situations and applies them when unexpected situations occur.",
//   "Understands the characteristics of the company’s products and can provide accurate information to customers or business partners.",
//   "Can efficiently obtain necessary information using various methods.",
//   "Takes action immediately and delivers quick results.",
//   "Can remain calm even in difficult situations.",
//   "Can perform required tasks accurately according to their intended purpose.",
//   "Has acquired the skills and knowledge necessary for production and manufacturing operations.",
//   "Is always aware of personal responsibility and fulfills assigned roles.",
//   "Can create a positive impression through customer service and external communication.",
//   "Has acquired the necessary knowledge and skills to perform design-related work.",
//   "Can speak, develop logic, and act in ways that persuade others.",
//   "Can generate new ideas without being bound by preconceived notions.",
//   "Possesses curiosity about unknown things and strives to understand underlying principles and phenomena.",
//   "Can collaborate with team members and act to achieve goals.",
//   "Can derive balanced conclusions that all stakeholders with different interests can agree upon.",
//   "Can build trust-based relationships with stakeholders to ensure smooth business or negotiations.",
//   "Can persist through difficult tasks, negotiations, or heavy workloads without giving up.",
//   "Can accurately recognize situations and make quick decisions.",
//   "Has acquired basic manners necessary to avoid making others uncomfortable in the workplace.",
//   "Has acquired knowledge and techniques required for quality control.",
//   "Has acquired essential knowledge needed for real estate or construction-related work.",
//   "Can convey information in a way that the other person understands and influence their actions.",
//   "Can plan activities, create schedules, and manage progress to ensure project success.",
//   "Can clearly express ideas in writing.",
//   "Can analyze the mechanisms behind information and events according to objectives.",
//   "Understands how to create products/services that many customers want and how to encourage customers to buy.",
//   "Continuously gathers new knowledge and know-how in a practical manner.",
//   "Can efficiently procure necessary resources—people, goods, money, information—to achieve objectives.",
//   "Can evaluate all possible options to fulfill assigned roles and put them into practice.",
//   "Can systematically organize collected information and summarize key points concisely.",
//   "Can proactively lead the team toward achieving goals and roles.",
//   "Can identify key points from collected information or communication and express them accurately in different words.",
//   "Understands relationships between matters and the structure of problems, and can explain them logically.",
//   "Can create documents that clearly convey messages to the reader using appropriate text and diagrams.",
//   "Has acquired knowledge of laws required for business operations.",
//   "Has acquired the methods and knowledge necessary for consulting.",
//   "Has acquired the methods and knowledge necessary for business management.",
//   "Has acquired the methods and knowledge necessary for human resources operations.",
//   "Has acquired the techniques and knowledge required for production management."
// ],

  AdditionalDetails: [
      "ファイナンシャルプランナー（FP）の資格や、資産運用についてアドバイスできる知識を持っている",
      "業務で活用できる必要最低限の情報システムに関する知識を習得している",
      "ExcelやWordなど、パソコン業務を行う上で必要な基本ソフトを使いこなせる",
      "商品の販売に必要な知識や能力を発揮できる",
      "法人向け営業を行うための必要最低限の知識を習得している",
      "入手した知識やノウハウを互いに関連付けて利用したり、基本的な知識を複雑な問題の解決に活用したりできる",
      "外国人との業務を遂行する上で、コミュニケーションに問題がない語学力がある",
      "発生した問題の原因を理解し、取り組むべき課題を導き出すことができる",
      "情報や素材を整理し、目的に合わせて新たな活動計画を立案することができる",
      "生命や財産に影響を与えるリスクをあらかじめ想定し、それらの回避方法を準備して実行できる",
      "相手の立場を理解し、業務や交渉をスムーズに運ぶための配慮ができる",
      "誰もが納得できる視点を持ち、それを表現できる",
      "相手と協力し合いながら作業を進めることができる",
      "金融商品の販売、資金計画、ローン計画などの金融業務を行う上で必要な知識を持ち、それらを活用できる",
      "目標達成までの活動において、いつまでに何をしなければならないかを考え、それに沿った行動ができる",
      "入出金処理や伝票／納品書／請求書発行など、経理に関する業務を遂行する上で必要な知識を習得している",
      "未知の物事に対して幅広く興味を持ち、自主的に情報収集したり取り組んだりできる",
      "意見や立場が異なる相手と話し合い、より自分の意図に近い合意形成ができる",
      "必要な行動を自発的に実行できる",
      "顧客の立場に立って物事を捉え、顧客の思考やニーズを理解することができる",
      "相手の意図を理解し、相手の理解度に応じて話す内容や話し方を変えることにより、的確に情報を伝えることができる",
      "自分と異なる意見に対して否定的にならず、まずは聞き入れ、その中で良い部分を取り入れることができる",
      "発生が予想される状況への対応策をあらかじめ準備し、予期しない状況に遭遇した際には準備していた対策を活用して対処できる",
      "志望する企業の商品の特性を正確に理解し、顧客や取引先に対して適切な情報を提供することができる",
      "必要な情報を、さまざまな手段を用いて効率的に入手できる",
      "やるべきことにすぐに取り組み、素早く結果を出す",
      "不利な状況においても平常心を保つことができる",
      "果たすべき作業を、想定された意図の通り間違うことなく遂行できる",
      "生産・製造活動を行う上で必要な技術や知識を習得している",
      "自身の責任を常に意識し、与えられた役割を全うすることができる",
      "接客や外部とのコミュニケーションを通じて、相手に好印象を与えることができる",
      "設計業務を行う上で必要な技術や知識を習得している",
      "相手を納得させるような話し方、論理展開、行動ができる",
      "過去に存在しない物や考え方を、固定概念にとらわれず発想できる",
      "未知の物事に対して好奇心を抱き、その背景にある原理や現象を知ろうと努力する",
      "チームメンバーと協力し合いながら、目標を達成するために行動できる",
      "利害の異なる関係者全員が納得できるような、バランスの取れた結論を導き出すことができる",
      "業務や交渉をスムーズに進めるために、ステークホルダーとの信頼関係を構築することができる",
      "困難な業務や交渉を進めたり、大量の作業を処理する必要がある際に、諦めずに取り組むことができる",
      "物事やそれを取り巻く状況を正しく認識し、迅速な意思決定ができる",
      "仕事を行う上で、相手を不愉快にさせないための基本的なマナーを身に付けている",
      "品質管理を行う上で必要な技術や知識を習得している",
      "不動産・建築の業務を行う上で必要な知識を習得している",
      "伝えたいことを相手に理解されるように伝えて、相手の行動を促すことができる",
      "プロジェクトを成功させるための各活動の計画立案、日程表の作成、進捗管理などができる",
      "文章で、読み手に伝えたいことを的確に表現できる",
      "目的に応じて情報や事象のメカニズムを解き明かすことができる",
      "多くの顧客が求める商品・サービスの作り方のほか、顧客が商品を購入したくなる方法について理解している",
      "新しい知識やノウハウを、常に実践的に収集している",
      "必要な人・物・金・情報などの資源を効率的に調達し、目的を達成できる",
      "与えられた役割を果たすためにあらゆる手段を検討し、それらを実行に移すことができる",
      "収集した情報を体系的に整理し、短い言葉でその要点をまとめることができる",
      "チームの目標や役割の達成に向け、主体的にチームをゴールへ導くことができる",
      "収集した情報やコミュニケーションをする相手の言葉の要点を把握し、別の言葉で的確に表現できる",
      "物事の関係性や問題の原因の構造を理解し、筋道を立てて説明できる",
      "伝えたいことが正しく読み手に理解されるよう、適切な文章や図表を交えた資料を作成することができる",
      "業務上で必要となる法律に関する知識を習得している",
      "コンサルティングを行う上で必要な手法や知識を習得している",
      "経営を行う上で必要な手法や知識を習得している",
      "人事業務を行う上で必要な手法や知識を習得している",
      "生産管理を行う上で必要な技術や知識を習得している"
    ],
    Questions:[
        "自分の強みとなる「1つ目の知識や能力」をプルダウンから選択してください。",
        "自分の強みとなる「2つ目の知識や能力」をプルダウンから選択してください。",
        `その強みを発揮した大学時代の「活動名」を「〇〇の活動」という形式で端的に記入してください。`,
        `その活動の中での「活動の目的や目標」を記入してください。
  記入する際は「○○することを目的（目標）にしました」と続くように記入してください`,
          `その活動でのあなたが「担った役割」を記入してください。
  記入する際は「○○することことが自身の役割でした」と続くように記入してください`,
          `その活動での課題を記入してください。
  課題とは、乗り越えることが困難だと感じたことを端的に記入してください。
  記入する際は「○○こと」と続くように記入してください。`,
          `前項目で記入した課題に対してどのように取り組んだか記入してください。
  記入する際は「○○ことを意識した」と続くように記入してください。`,
          `その活動を通じて、どのような結果や成果を上げたか記入してください`,
        `「志望企業の正式名称」を記入してください。
  （株式会社等の法人形態は省いてください）`,
        "志望している企業のＴＯＰページのアドレスを入力してください。",
        `志望企業の「ミッションや理念」をホームページから探してきて記入してください。`,
        `あなたが魅力を感じる「企業理念・ビジョン・ミッション」「事業内容」「具体的な仕事内容」を記載してください。`,
        `なぜその会社に魅力を感じるのか、自分自身の経験やその中で感じたこと、考えたことも含めて説明してください。`
    ]
};

export default Constants;
